accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("<int:pk>", views.detail, name="detail"),
    path("update/", views.update, name="update"),
    path("logout/", views.logout, name="logout"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("review/", include("review.urls")),
]

review/urls.py
from django.urls import path
from . import views

app_name = "review"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("detail/<int:pk>", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    pass

review/models.py
from django.db import models

# Create your models here.


class Review(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    movie_name = models.CharField(max_length=30)
    grade = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "password1",
            "password2",
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
            "email",
        )

review/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["title", "content", "movie_name", "grade"]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

# from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserChangeForm, CustomUserCreationForm


# Create your views here.
def index(request):
    user = get_user_model().objects.all()
    context = {
        "user": user,
    }
    return render(request, "accounts/index.html", context)


def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        "user": user,
    }
    return render(request, "accounts/detail.html", context)


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("accounts:index")
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "accounts:index")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect("accounts:index")


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:detail", request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)

review/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from .models import Review
from .forms import ReviewForm


# Create your views here.


def index(request):
    review = Review.objects.order_by("pk")
    context = {
        "review": review,
    }
    return render(request, "review/index.html", context)


def create(request):
    if request.method == "POST":
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review_form.save()
            return redirect("review:index")
    else:
        review_form = ReviewForm()
    context = {
        "review_form": review_form,
    }
    return render(request, "review/new.html", context=context)


def detail(request, pk):
    # 특정 글을 가져온다.
    review = Review.objects.get(pk=pk)
    # template에 객체 전달
    context = {
        "review": review,
    }
    return render(request, "review/detail.html", context)


def update(request, pk):
    review = Review.objects.get(pk=pk)
    if request.method == "POST":
        # POST : input 값 가져와서, 검증하고, DB에 저장
        review_form = ReviewForm(request.POST, instance=review)
        if review_form.is_valid():
            # 유효성 검사 통과하면 저장하고, 상세보기 페이지로
            review_form.save()
            return redirect("review:detail", review.pk)
    else:
        # GET : Form을 제공
        review_form = ReviewForm(instance=review)
    context = {
        "review_form": review_form,
    }
    return render(request, "review/update.html", context)


def delete(request, pk):

    review = Review.objects.get(id=pk)
    review.delete()

    return redirect("review:index")

accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block title %}
  <title>{{user.username}}님의 페이지</title>
{% endblock title %}

{% block body %}
  <h1 class="mb-4">{{ user.username }}님의 프로필</h1>

  <h2>안녕하세요
    {{ user.last_name }}{{ user.first_name }}입니다.<h2>
      <h2>{{user.email}}</h2>

      <img src="https://i.pinimg.com/564x/40/dc/35/40dc35f144db1b3a280fc599a1886e7d.jpg" alt="">

      <p>
        <button type="button" class="btn btn-secondary mt-3 mb-2">
          <a class="text-white text-decoration-none" href="{% url 'accounts:index' %}">홈으로</a>
        </button>
      </p>

    {% endblock body %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}
  <title>HOME</title>
{% endblock title %}

{% block body %}
  <h1 class="text-center mt-5 text-success">Hello!</h1>


    <h1 class="text-center my-4">회원 목록</h1>
     <div class="col-12">
      <table class="table table-bordered">
        <tr>
         <thead class="table-dark text-center fs-4">
          <th>pk</th>
          <th>username</th>
          <th>email</th>
          <th>first_name</th>
          <th>last_name</th>
         </thead>
        </tr>
        <tbody>
          {% for u in user %}
            <tr class="text-center">
              <td class="fs-4">{{u.pk}}</td>
              <td>
                <a class="fs-4 text-decoration-none" href="{% url 'accounts:detail' u.pk  %}">{{u.username}}</a>
              </td>
              <td class="fs-4">{{u.email}}</td>
              <td class="fs-4">{{u.first_name}}</td>
              <td class="fs-4">{{u.last_name}}</td>
            </tr>
        </tbody>

        {% endfor %}
      </table>

      {% if request.user.is_authenticated %}
      <button type="button" class="btn btn-dark mt-2 mb-2">
        <a class="text-white text-decoration-none" href="{% url 'review:index' %}">리뷰목록</a>
            </button>
      {% endif %}      


  {% endblock body %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}
  <title>로그인</title>
{% endblock title %}

{% block body %}
<h1>로그인</h1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
    
</form>
<button type="button" class="btn btn-dark mt-3">
    <a class="text-white text-decoration-none text-end" href="{% url 'accounts:signup' %}">회원 가입</a>
  </button>
  <p><button type="button" class="btn btn-secondary mt-3 mb-2">
    <a class="text-white text-decoration-none" href="{% url 'accounts:index' %}">홈으로</a>
        </button></p>

{% endblock body %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}
  <title>회원 가입</title>
{% endblock title %}

{% block body %}
<h1>회원 가입</h1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}

</form>
<button type="button" class="btn btn-dark mt-2 mb-2">
    <a class="text-white text-decoration-none" href="{% url 'accounts:index' %}">홈으로</a>
        </button>

{% endblock body %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}
<title>내 정보 수정</title>
{% endblock title %}

{% block body %}
  <h1>프로필 업데이트</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
  </form>
  <button type="button" class="btn btn-secondary mt-3 mb-2">
    <a class="text-white text-decoration-none" href="{% url 'accounts:index' %}">홈으로</a>
  </button>
{% endblock body %}

config/templates/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}{% endblock title%}

    {% bootstrap_css %}
    {% block css %}{% endblock css %}
  </head>
  <nav class="navbar navbar-expand" style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <ul class="navbar-nav me-auto mb-lg-0">
        <li class="nav-item">
          <button type="button" class="btn btn-danger ms-2">
            <a class="text-white text-decoration-none" href="{% url 'accounts:index' %}">HOME</a>
          </button>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item mx-2">
            <a class="navbar-brand fw-bold m-0" href="{% url 'accounts:detail' request.user.pk %}">{{ request.user.username }}</a>

            <li class="nav-item mx-2">
              <button type="button" class="btn btn-dark">
                <a class="text-white text-decoration-none" href="{% url 'accounts:update' %}">
                  정보수정</a>
              </button>
            </li>

          {% else %}
            <li class="nav-item mt-1 ms-2">
              <a class="navbar-brand fw-bold" href="#">비회원</a>
            </li>

          {% endif %}

          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <button type="button" class="btn btn-dark">
                <a class="text-white text-decoration-none" href="{% url 'accounts:logout' %}">
                  로그아웃</a>
              </button>
            {% else %}
              <button type="button" class="btn btn-dark me-2">
                <a class="text-white text-decoration-none" href="{% url 'accounts:login' %}">
                  로그인</a>
              </button>
              <li class="nav-item">
                <button type="button" class="btn btn-dark">
                  <a class="text-white text-decoration-none" href="{% url 'accounts:signup' %}">회원 가입</a>
                </button>
              </li>

            </div>
          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container mt-5 col-12">
      {% block body %}{% endblock body %}
    </div>
    {% bootstrap_javascript %}
  </body>

</html>

review/templates/review/detail.html
{% extends 'base.html' %}

{% block body %}
  <div class="container-lg my-4">

    <h2 class="">영화 제목 :
      {{review.movie_name}}
      // 평점 :
      {{review.grade}}
    </h2>
    <h2 class="my-2">리뷰명 :
      {{review.title}}</h2>
    <div class="card mb-4" style="width: 800px; height:600px;">
      <div class="card-body">
        <p class="card-text fs-3">{{ review.content }}</p>
      </div>
    </div>
    <button type="button" class="btn btn-primary">
      <a class="text-white" href="{% url 'review:update' review.pk %}">
        수정
      </a>
    </button>
    <button type="button" class="btn btn-danger">
      <a class="text-white" href="{% url 'review:delete' review.pk %}">
        삭제
      </a>
    </button>
    <button type="button" class="btn btn-dark">
      <a class="text-white" href="{% url 'review:index'%}">홈으로</a>

    </a>
  </button>
</div>
{% endblock body %}

review/templates/review/index.html
{% extends 'base.html' %}

{% block body %}

  {% for r in review %}
    <div class="accordion" id="accordionExample">

      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">

          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">

            {{r.pk}}
            :
            {{r.title}}
          </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <p>
              <strong>영화제목:
                {{r.movie_name}}</strong>
            </p>
            <p>{{r.content}}</p>
            <a class="text-decoration-none text-right text-end text-hover" href="{% url 'review:detail' r.pk %}">상세 보기</a>
          </div>
        </div>

      </div>

    </div>
  {% endfor %}

  <button type="button" class="btn btn-secondary text-end mt-3 mb-2">
    <a class="nav-link fw-bold active fs-5 text-end" href="{% url 'review:create' %}">리뷰 추가</a>
  </button>
</div>

</div>

{% endblock body %}

review/templates/review/new.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}

  <div class="container mx-4 my-4">
    <h1 class="fw-bold my-4">리뷰 작성</h1>
    <form action="{% url 'review:create' %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form review_form %}
      <div class="d-grid gap-2">
        {% bootstrap_button content="작성완료" button_type="submit" class="btn btn-primary col-12" %}
      </div>
    </form>

  </form>
  <button type="button" class="btn btn-success mt-2">
    <a class="text-white" href="{% url 'review:index'%}">홈으로</a>

  {% endblock body %}

review/templates/review/update.html
{% extends 'base.html' %}

{% block body %}

  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

  <div class="containter mx-5">
    <div class="row mx-5">
      <div class="col mx-5">
        <h1 class="fw-bold my-2">리뷰 수정</h1>
        <form action="" method="POST">
          {% csrf_token %}
          {% bootstrap_form review_form %}
          <div class="d-grid gap-2 mb-4">
            {% bootstrap_button content="수정완료" button_type="submit" class="btn-btn-primary col-12"  %}
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock body %}